# Generated by Django 2.2.2 on 2019-06-18 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('cma', models.IntegerField()),
                ('phone', phone_field.models.PhoneField(help_text='Contact Number', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=30)),
                ('urbanization', models.CharField(max_length=30)),
                ('user_user_model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=1000000000000000)),
                ('is_recurring', models.BooleanField(default=False)),
                ('date', models.DateField(default=None, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo_app.Events')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo_app.EventRegistration')),
            ],
        ),
        migrations.CreateModel(
            name='AdminToUserMAp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('Non_Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminToEventMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo_app.Events')),
            ],
        ),
    ]
